### ISSUE TITLE
What is the use case for this type of RAW images?

### ISSUE THREAD

**Issue by TyrfingMjolnir** [nattfalk/iff2raw#2]
What is the use case for this type of RAW images? What would it take to convert to JPEG or PNG, opposed to RAW, i e

**Comment by TyrfingMjolnir** [comment]
I have a couple of thousand Amiga IFF ILBM files that I drew mainly in Brilliance and DeLuxePaint

All of the files in this backup while run through like
```
for file in */*/*/*.LBM ; do /opt/local/dev/iff2raw/iff2raw -v -i $file; done
```
gives the same output:

iff2raw 0.1 Copyright (c) Michael Nattfalk 2019

IFF loader
Found BMHD chunk
 - Image size: 0x0
 - Number of bitplanes: 0
Found BODY chunk
 - Image data compressed

== RAW writer ==
No output filename specified!

**Comment by nattfalk** [comment]
> What is the use case for this type of RAW images? What would it take to convert to JPEG or PNG, opposed to RAW, i e

This tool was written for a friend needing it for a specific purpose which is to extract the bitplane data into RAW files (and palette data into separate binary or ASM files) which are commonly used within the demoscene in intros and demos.
It was never intended as a conversion tool towards other images formats.
But please feel free to fork it and extend it in any way you like :)
